import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Alert,
} from 'react-native';
import { Button } from '../components/Button';
import { COLORS, FONT_SIZES, SPACING, DIMENSIONS } from '../constants/theme';
import { StorageService } from '../utils/storage';
import { MockRevenueCatService } from '../services/revenuecat';

interface PremiumFeature {
  icon: string;
  title: string;
  description: string;
}

const PREMIUM_FEATURES: PremiumFeature[] = [
  {
    icon: '🚀',
    title: 'Unlimited Affirmations',
    description: 'Generate as many affirmations as you want, whenever you want',
  },
  {
    icon: '🎯',
    title: 'Category Selection',
    description: 'Choose from Motivation, Love, Focus, and Gratitude categories',
  },
  {
    icon: '🤖',
    title: 'AI-Powered Affirmations',
    description: 'Get personalized affirmations generated by advanced AI',
  },
  {
    icon: '📱',
    title: 'Advanced Notifications',
    description: 'Customizable notification times and frequency',
  },
  {
    icon: '💾',
    title: 'Unlimited Favorites',
    description: 'Save as many affirmations as you want to your favorites',
  },
  {
    icon: '🎨',
    title: 'Premium Themes',
    description: 'Access exclusive app themes and customization options',
  },
];

export const PremiumScreen: React.FC = () => {
  const [isPremium, setIsPremium] = useState(false);
  const [loading, setLoading] = useState(false);
  const [restoring, setRestoring] = useState(false);

  useEffect(() => {
    checkPremiumStatus();
  }, []);

  const checkPremiumStatus = async () => {
    try {
      const premium = await MockRevenueCatService.checkPremiumStatus();
      setIsPremium(premium);
    } catch (error) {
      console.error('Error checking premium status:', error);
    }
  };

  const handlePurchasePremium = async () => {
    setLoading(true);
    
    try {
      Alert.alert(
        'Upgrade to Premium',
        'This will unlock all premium features for $2.99/month. Continue?',
        [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Purchase',
            onPress: async () => {
              try {
                const success = await MockRevenueCatService.purchasePackage();
                if (success) {
                  setIsPremium(true);
                  Alert.alert(
                    'Welcome to Premium! ✨',
                    'You now have access to unlimited affirmations, AI-generated content, and all premium features!',
                    [{ text: 'Awesome!', style: 'default' }]
                  );
                } else {
                  Alert.alert('Purchase Failed', 'Please try again later.');
                }
              } catch (error) {
                console.error('Purchase error:', error);
                Alert.alert('Purchase Failed', 'Please try again later.');
              }
            },
          },
        ]
      );
    } catch (error) {
      console.error('Error initiating purchase:', error);
      Alert.alert('Error', 'Unable to process purchase. Please try again later.');
    } finally {
      setLoading(false);
    }
  };

  const handleRestorePurchases = async () => {
    setRestoring(true);
    
    try {
      const success = await MockRevenueCatService.restorePurchases();
      if (success) {
        setIsPremium(true);
        Alert.alert(
          'Purchases Restored! ✨',
          'Your premium features have been restored.',
          [{ text: 'Great!', style: 'default' }]
        );
      } else {
        Alert.alert(
          'No Purchases Found',
          'We could not find any previous purchases to restore.',
          [{ text: 'OK', style: 'default' }]
        );
      }
    } catch (error) {
      console.error('Error restoring purchases:', error);
      Alert.alert('Error', 'Unable to restore purchases. Please try again later.');
    } finally {
      setRestoring(false);
    }
  };

  const renderFeature = (feature: PremiumFeature, index: number) => (
    <View key={index} style={styles.featureContainer}>
      <Text style={styles.featureIcon}>{feature.icon}</Text>
      <View style={styles.featureContent}>
        <Text style={styles.featureTitle}>{feature.title}</Text>
        <Text style={styles.featureDescription}>{feature.description}</Text>
      </View>
    </View>
  );

  if (isPremium) {
    return (
      <ScrollView style={styles.container} contentContainerStyle={styles.contentContainer}>
        <View style={styles.premiumStatusContainer}>
          <Text style={styles.premiumStatusIcon}>✨</Text>
          <Text style={styles.premiumStatusTitle}>Premium Active</Text>
          <Text style={styles.premiumStatusSubtitle}>
            You have access to all premium features!
          </Text>
        </View>

        <View style={styles.featuresContainer}>
          <Text style={styles.sectionTitle}>Your Premium Features</Text>
          {PREMIUM_FEATURES.map(renderFeature)}
        </View>

        <View style={styles.buttonContainer}>
          <Button
            title="Manage Subscription"
            onPress={() => Alert.alert('Info', 'Subscription management coming soon!')}
            variant="secondary"
          />
        </View>
      </ScrollView>
    );
  }

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.contentContainer}>
      <View style={styles.header}>
        <Text style={styles.title}>Upgrade to Premium</Text>
        <Text style={styles.subtitle}>
          Unlock unlimited affirmations and exclusive features
        </Text>
      </View>

      <View style={styles.pricingContainer}>
        <View style={styles.pricingCard}>
          <Text style={styles.pricingTitle}>Premium Monthly</Text>
          <Text style={styles.pricingPrice}>$2.99<Text style={styles.pricingPeriod}>/month</Text></Text>
          <Text style={styles.pricingDescription}>
            Cancel anytime • Full access to all features
          </Text>
        </View>
      </View>

      <View style={styles.featuresContainer}>
        <Text style={styles.sectionTitle}>Premium Features</Text>
        {PREMIUM_FEATURES.map(renderFeature)}
      </View>

      <View style={styles.buttonContainer}>
        <Button
          title="Start Premium - $2.99/month"
          onPress={handlePurchasePremium}
          loading={loading}
          variant="premium"
        />
        
        <Button
          title="Restore Purchases"
          onPress={handleRestorePurchases}
          loading={restoring}
          variant="secondary"
          style={styles.restoreButton}
        />
      </View>

      <Text style={styles.disclaimer}>
        Premium subscription auto-renews unless cancelled. Terms and conditions apply.
      </Text>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  contentContainer: {
    paddingBottom: SPACING.EXTRA_LARGE,
  },
  header: {
    alignItems: 'center',
    paddingHorizontal: SPACING.LARGE,
    paddingTop: SPACING.EXTRA_LARGE,
    paddingBottom: SPACING.LARGE,
  },
  title: {
    fontSize: FONT_SIZES.TITLE,
    fontWeight: 'bold',
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.SMALL,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: FONT_SIZES.MEDIUM,
    color: COLORS.TEXT_SECONDARY,
    textAlign: 'center',
    lineHeight: 22,
  },
  premiumStatusContainer: {
    alignItems: 'center',
    paddingHorizontal: SPACING.LARGE,
    paddingTop: SPACING.EXTRA_LARGE,
    paddingBottom: SPACING.LARGE,
  },
  premiumStatusIcon: {
    fontSize: 64,
    marginBottom: SPACING.MEDIUM,
  },
  premiumStatusTitle: {
    fontSize: FONT_SIZES.TITLE,
    fontWeight: 'bold',
    color: COLORS.PREMIUM,
    marginBottom: SPACING.SMALL,
  },
  premiumStatusSubtitle: {
    fontSize: FONT_SIZES.MEDIUM,
    color: COLORS.TEXT_SECONDARY,
    textAlign: 'center',
  },
  pricingContainer: {
    paddingHorizontal: SPACING.LARGE,
    marginBottom: SPACING.LARGE,
  },
  pricingCard: {
    backgroundColor: COLORS.CARD_BACKGROUND,
    borderRadius: DIMENSIONS.BORDER_RADIUS,
    padding: SPACING.LARGE,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.PREMIUM,
  },
  pricingTitle: {
    fontSize: FONT_SIZES.LARGE,
    fontWeight: 'bold',
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.SMALL,
  },
  pricingPrice: {
    fontSize: FONT_SIZES.TITLE,
    fontWeight: 'bold',
    color: COLORS.PREMIUM,
    marginBottom: SPACING.SMALL,
  },
  pricingPeriod: {
    fontSize: FONT_SIZES.MEDIUM,
    color: COLORS.TEXT_SECONDARY,
  },
  pricingDescription: {
    fontSize: FONT_SIZES.SMALL,
    color: COLORS.TEXT_SECONDARY,
    textAlign: 'center',
  },
  featuresContainer: {
    paddingHorizontal: SPACING.LARGE,
  },
  sectionTitle: {
    fontSize: FONT_SIZES.LARGE,
    fontWeight: 'bold',
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.LARGE,
    textAlign: 'center',
  },
  featureContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: SPACING.LARGE,
    backgroundColor: COLORS.CARD_BACKGROUND,
    padding: SPACING.MEDIUM,
    borderRadius: DIMENSIONS.BORDER_RADIUS,
  },
  featureIcon: {
    fontSize: 24,
    marginRight: SPACING.MEDIUM,
  },
  featureContent: {
    flex: 1,
  },
  featureTitle: {
    fontSize: FONT_SIZES.MEDIUM,
    fontWeight: 'bold',
    color: COLORS.TEXT_PRIMARY,
    marginBottom: SPACING.SMALL,
  },
  featureDescription: {
    fontSize: FONT_SIZES.SMALL,
    color: COLORS.TEXT_SECONDARY,
    lineHeight: 18,
  },
  buttonContainer: {
    paddingHorizontal: SPACING.LARGE,
    marginTop: SPACING.LARGE,
  },
  restoreButton: {
    marginTop: SPACING.MEDIUM,
  },
  disclaimer: {
    fontSize: FONT_SIZES.SMALL,
    color: COLORS.TEXT_LIGHT,
    textAlign: 'center',
    paddingHorizontal: SPACING.LARGE,
    marginTop: SPACING.LARGE,
  },
});